### ISSUE TITLE
BetQuestion entity에 보기 column추가

### ISSUE THREAD

**Issue by tjrdnjs1534** [DevKor-github/toky-back#3]
여러분 저희가 문제에 대한 선택할 수 있는 응답들의 보기들을 제공해야하는데 entity에 빠진 것 같습니다. 그래서 betQuestion에 @column choices: string[];
이렇게 해줘야할 거 같은데 어떻게 생각하시나요 ?

**Comment by yunz0926** [comment]
그렇네요 ,, ! 말한대로 추가해주면 될 것 같습니당

**Comment by tjrdnjs1534** [comment]
choices들이 어차피 몇 개 안될거 같아서 배열형으로 db에 넣는 방식으로 하겠습니다!

**Comment by tjrdnjs1534** [comment]
text 배열형으로 선언해서 넣어주겠습니다!
